site_name: Tiếng Trung - Khu học mở
site_description: Tự học Tiếng Trung thông qua các nguồn tài nguyên miễn phí trên Internet (Comprehensible Input & Immersion)
site_author: khuhocmo  
repo_url: https://github.com/daihocmo/tieng-trung
repo_name: Đóng góp & chỉnh sửa trang

nav:
  - 'Trang chủ': 'index.md'
  - 'Hướng dẫn': 
    - 'Tự học Tiếng Trung': 'guide.md'
    - 'Chữ Hán (Hànzì - 汉字)': 'hanzi.md'
    - 'Đọc Tiếng Trung': 'reading.md'
    - 'Immersion Tiếng Trung': 'immersion.md'
    - 'Mining': 'mining.md'
    - 'Cài đặt': 'setup.md'
  - 'Yomitan':
    - 'Hướng dẫn cài đặt Yomitan': 'yomitan.md'
  - 'Tài nguyên': 
    - 'Tài nguyên học': 'resources.md'
    - 'Nội dung Tiếng Trung': 'recommendations.md'
  - 'Khác':
    - 'Cộng đồng tự học': 'cong-dong.md'

theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - toc.follow
    - search.highlighting
    - search.share
    - search.suggest
  favicon: img/logo.svg
  logo: img/logo.svg
  icon:
    repo: fontawesome/brands/github
  name: material
  language: vi


markdown_extensions:
  - meta
  - admonition
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      
      
plugins:
  - search
  - open-in-new-tab

extra:
  generator: false